server:
  address: 0.0.0.0
  port: 8080

spring:
  application:
    name: rag-assistant
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/rag_db}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
  ai:
    vectorstore:
      pgvector:
        dimensions: 768
        initialize-schema: true
    ollama:
      embedding:
        model: nomic-embed-text
      base-url: ${SPRING_AI_OLLAMA_BASE_URL:http://localhost:11434}
      chat:
        model: gemma3
  security:
    user:
      name: ""

app:
  jwt:
    secret: "e9871ce4-8ec5-49d9-9901-00aa88908959"
    expiration-ms: 3600000
