server:
  port: 8080

spring:
  application:
    name: rag-assistant
  web:
    resources:
      static-locations: classpath:/static/
  ai:
    vectorstore:
      pgvector:
        dimensions: 768
        initialize-schema: true
    ollama:
      embedding:
        model: nomic-embed-text
      base-url: http://localhost:11434
      chat:
        model: gemma3
  datasource:
    url: jdbc:postgresql://localhost:5432/rag_db
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver